### ISSUE TITLE
Missed files

### ISSUE THREAD

**Issue by radiolondra** [Randomize163/FSDefender#1]
"FSDKmCommonInclude.h" is missed

**Comment by radiolondra** [comment]
No, sorry, the file is there but VS2017 cannot open it:
impossible to open the error code "FSDKmCommonInclude.h" of the original file (E1696)
Bah?

**Comment by Randomize163** [comment]
Hi,

This is very small file: https://github.com/Randomize163/FSDefender/blob/master/FSDKmCommonUtils/FSDKmCommonInclude.h

I think your problem is more related to Visual Studio. Ensure that no other programs use this file.
